In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.data import Dataset, TFRecordDataset
from tensorflow.data.experimental import TFRecordWriter
from tensorflow.train import BytesList, FloatList, Int64List
from tensorflow.train import Example, Features, Feature

In [9]:
s = '[1,2]'
t = eval(s)
t = tf.convert_to_tensor(t, dtype=tf.float32)
print(t)
print(t.shape)
type(t)

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
(2,)


tensorflow.python.framework.ops.EagerTensor

# serialize a tensor

In [6]:
x = tf.constant([[1, 2], [3, 4]], dtype=tf.uint8)
print('x:', x, '\n')

x_bytes = tf.io.serialize_tensor(x)
print('x_bytes:', x_bytes, '\n')

print('x:', tf.io.parse_tensor(x_bytes, out_type=tf.uint8))


x: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=uint8) 

x_bytes: tf.Tensor(b'\x08\x04\x12\x08\x12\x02\x08\x02\x12\x02\x08\x02"\x04\x01\x02\x03\x04', shape=(), dtype=string) 

x: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=uint8)
